services:
  - type: web
    name: konseil-cabinet-conseil
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.18
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true

databases:
  - name: konseil-db
    databaseName: konseil
    user: konseil_user
    plan: free 